### ISSUE TITLE
Hamburger menu doesn't work on iOS

### ISSUE THREAD

**Issue by lunaryorn** [jekyll/minima#80] opened 2016-11-09 21:57 UTC
I'm using minima for http://www.lunaryorn.com and just noticed that the hamburger menu doesn't work on iPhone/iOS: When I tap the icon the menu doesn't pop up.   I went through a couple of phones on browerstack and could reproduce the problem with Safari on iPhones, whereas the menu works fine on Android devices with Google Chrome.  Note the issues does also not appear in the "responsive" design modes of Safari and Chrome on desktop.

I'm not so familiar with CSS, and don't really understand how the menu's implemented in Minima, so I'm at a loss.  I don't even know how to debug the issue given that it only occurs on the real phone.

Would really appreciate any help :)

**Comment by mgerzabek** [comment] 2016-11-11 03:01
Same here. Just stumbled upon this wonderful starter theme and see the same behaviour as Sebastian is describing.
Thanks to the community for this theme, a helpful starting point for newcomers to Jekyll.

**Comment by melaniewalsh** [comment] 2016-11-14 22:43
I'm also having the same problem! iOS doesn't respond to "%:hover trigger"

**Comment by melaniewalsh** [comment] 2016-11-16 16:06
Hey! I figured out that if you add a dummy onclick handler `onclick = "void(0)"` into the span element of the header html, then iOS recognizes will recognize it as a clickable element.

**Comment by DirtyF** [comment] 2016-11-16 17:58
@melaniewalsh interested in submitting a PR to fix this?

**Comment by mabelvj** [comment] 2016-11-18 14:12
Solved my problem! Nice workaround @melaniewalsh! Confirmed to be working! Thanks!

Added like this in:
``` <nav class="site-nav">
      <span class="menu-icon" onclick = "void(0)"> ````

**Comment by RodenLuo** [comment] 2016-12-08 23:35
Good solution already. Just one more step forward for people who want to close the drop-down menu.

It needs another "clickable element" to help. One can put it in `<header>` or even the first `<div>` in `<Body>` if you want. A live [demo](http://riverlight.blog/2016/12/08/Jekyll-Nav-Bar-iOS-Compatibility.html), putting in `<header>`. Then you can click the other area to close the menu. (Inspired because I can close it when click on link (`<a>`) area.)

Since the whole element will flicker when one clicks it. Making the drop down menu into a click version would be good. Or :hover on desktop, click on touch.

**Comment by Ambrosiani** [comment] 2017-01-08 10:37
As RodenLuo pointed out, one should be able to collapse the menu by tapping the hamburger icon once again. I don't know how to do this in pure css unfortunately. Avoiding javascript would be nice.

**Comment by alxn** [comment] 2017-02-24 15:50
I've been reading up on this, while there seems to be a movement [against hamburgers](https://lmjabreu.com/post/why-and-how-to-avoid-hamburger-menus/), there's plenty of examples of pure-CSS ones: [1](https://codepen.io/SitePoint/pen/uIemr), [2](https://codepen.io/jlnljn/pen/LkXoBb).

I think these are all using a `<input>` for the clickable.

**Comment by alxn** [comment] 2017-02-26 22:18
Could everyone try out my CSS fix in #111 and see if it works for them?

**Closed** 2017-04-07 16:52 UTC

**Comment by SeFore** [comment] 2018-12-18 09:24
I added  onclick="void(0)" to the span but doesn't work with me. 
Any new suggestions?

Thanks.

**Comment by hubosh** [comment] 2019-01-27 07:55
@SeFore Were you able to find a solution ?
