### ISSUE TITLE
Quickstart instructions result in unstyled page.

### ISSUE THREAD

**Issue by Catsync** [jekyll/minima#34] opened 2016-09-07 18:03 UTC
I followed the [quickstart instructions](http://jekyllrb.com/docs/quickstart/).

When I view the default site generated by `jekyll new`, it's trying to fetch the css from `http://example.com/css/main.css` instead of my local main.css file.

I can set my _config.yml to have `url: ""` and that fixes the issue, but possibly it's something that should be fixed in the minima theme?

**Comment by DirtyF** [comment] 2016-09-07 23:12
We could leave this field empty and add a comment next to it, but you're gonna have to set this value at one time or another if you wanna go into production.

**Comment by eliza411** [comment] 2016-09-08 00:40
Hi there. I ran into trouble here too. I haven't set up the DNS yet, so I'm trying to set the value here to an IP address, but the CSS won't load unless the url: value is set to "" or commented out.

The URL line looks like:  `url: "http://104.236.152.145"` I feel like I must be missing something obvious.

**Comment by ashmaroli** [comment] 2016-09-08 02:52
This bug is due to a recent change shipped with minima-1.1.0. Have opened a PR upstream to address this in a future release of Jekyll.

**Comment by ashmaroli** [comment] 2016-09-08 02:59
## Temporary Fix
Change the following line in your `_config.yml`
```yaml
url: "http://example.com" # the base hostname & protocol for your site
```
to following ( while in development ):
```yaml
url: "" # the base hostname & protocol for your site
```

_Note: Don't forget to update this line before going into production._

**Comment by ArazAbishov** [comment] 2016-09-08 15:22
Unfortunately, I have similar issue. CSS is not loaded by browser because url property in _config is not respected as should. Instead of https://example.com (specified in url property), jekyll generated wrong path to css file: http://example.com. 

This issue appeared as soon as minima 1.1.0 was released.

**Comment by benbalter** [comment] 2016-09-08 15:26
To confirm, the issue is that when URL is set, it tries to load the assets from the live URL, so locally it must be set to "" for the assets to load from the local source?

**Comment by ArazAbishov** [comment] 2016-09-08 15:29
In my case, url which is set in _config is ignored:

Here is the config file (https://github.com/ArazAbishov/arazabishov.github.io/blob/master/_config.yml#L9) and link to generated page: https://abishov.com

**Comment by benbalter** [comment] 2016-09-08 15:36
>  Here is the config file and link to generated page: https://abishov.com. If you inspect the page, css is not loaded because of the wrong path to it (instead of https (as specified in _config), it points to http, as the result browser blocks request).

Yep. If you hard code a URL, it will use that. You'll need to set the URL to HTTPS so that it can load the CSS.

**Comment by ArazAbishov** [comment] 2016-09-08 16:21
Yes, that's exactly what I did initially (it was working with minima 1.0.1, but was broken right after update).

**Comment by ashmaroli** [comment] 2016-09-08 16:27
your settings are correctly set to use `https://`
but your blog's [source-code](view-source:https://abishov.com/) shows `http://` references instead.

**Comment by ArazAbishov** [comment] 2016-09-08 16:31
That's right. Could it be caused by minima or configuration?

**Comment by ashmaroli** [comment] 2016-09-08 16:35
I'm able to build & serve your blog correctly, locally. So, my *guess* is there's a bug somewhere in the configuration for production environment.

**Comment by ArazAbishov** [comment] 2016-09-08 16:38
@ashmaroli Thanks a bunch. Let's wait for the comments of dev. team on this.

**Comment by ashmaroli** [comment] 2016-09-08 16:46
At the back of my head, I'm thinking of using a `Procfile` or `foreman` to force `bundle exec jekyll serve` production-side.
But yes, lets wait for an authorized comment.

**Comment by ashmaroli** [comment] 2016-09-08 17:16
@ArazAbishov, can you do a quick review of your repo settings and check if the ***Enforce HTTPS*** checkbox has been checked?

**Comment by ArazAbishov** [comment] 2016-09-08 17:30
@ashmaroli Oh, it seems github unchecked it automatically as soon as I have set up custom domain, but I still don't understand why this issue floated up after update of minima.

**Comment by ashmaroli** [comment] 2016-09-08 17:40
You can add that enforcement to the config file like so:
```yaml
enforce_ssl: abishov.com
```

**Comment by ashmaroli** [comment] 2016-09-08 17:50
To check if minima is really the cause behind this issue, add version 1.0.1 to your gemfile:
```ruby
gem "minima", "1.0.1"
```

**Comment by ArazAbishov** [comment] 2016-09-08 18:23
Tried to enforce SSL, did not help. Specifying minima version 1.0.1 did not work (github did not pick it up, still builds blog with minima 1.1.0).

**Comment by benbalter** [comment] 2016-09-08 18:57
Looking at https://github.com/jekyll/minima/blob/master/_includes/head.html#L9-L10, it looks like it should use `site.github.url` if present, otherwise falling back to the one in the config. @parkr I believe that was your doing. Do you think it should be reversed? 

In this case, the user has a custom domain, which `site.github.url` would then be HTTP, but the user has a proxy, so they actually do support HTTPS, thus the user specific option should override the GitHub specified option, not the other way around.

**Comment by parkr** [comment] 2016-09-09 00:00
> In this case, the user has a custom domain, which site.github.url would then be HTTP, but the user has a proxy, so they actually do support HTTPS, thus the user specific option should override the GitHub specified option, not the other way around.

It's a fairly new change so I'm fine with that.

**Comment by fvilers** [comment] 2016-09-09 06:51
@parkr I'm discovering GitHub Pages, Ruby & Jekyll. I don't understand why this change has been made to the head.html template. How can you verify that the CSS is correct if it always get downloaded from the remote server and not locally ? How can I set up the configuration to use the local CSS instead of the one hosted at GitHub?

**Comment by ashmaroli** [comment] 2016-09-09 07:30
I believe a _patch_ would only need a minor change:

now:
```
  {% assign custom_url = site.url | append: site.baseurl %}
  {% assign full_base_url = site.github.url | default: custom_url %}
```
patch:
```
  {% assign custom_url = site.url | append: site.baseurl %}
  {% assign full_base_url = custom_url | default: site.github.url %}
```
unless otherwise, Parker will be releasing a new version a.s.a.p

**Comment by ArazAbishov** [comment] 2016-09-09 08:24
@ashmaroli Thanks a lot. To be honest I don't want to fork minima or patch it manually (one of the reasons to use minima is ability to get it working by single property in _config). 

@parkr @benbalter How much time do you think it will take to fix it? If it is more than a week, I will probably switch proxy off and use plain HTTP scheme.

**Comment by benbalter** [comment] 2016-09-09 13:24
@ashmaroli I believe that is the correct fix. If you (or @ArazAbishov) were willing and able to submit a pull request to that end, I'd be glad to review and merge.

**Comment by ArazAbishov** [comment] 2016-09-09 15:17
@ashmaroli @benbalter Thanks a lot for the fix. When do you think new version with bugfix will be released?

**Closed** 2016-09-09 19:28 UTC

**Comment by Sjlver** [comment] 2016-09-28 14:15
I'd like to discuss this a bit further. To me, the question is: *why does the theme use an absolute URL for style sheets?*

I think having a non-empty `url:` in `_config.yaml` can be useful. It allows for things like `<link rel="canonical">` However, I don't think this URL should be used when referencing style sheets. Style sheets should be loaded relative to `baseurl`, so that developers can preview their site locally.

In other words, I believe the correct `head.html` would be this:

```html
  {% assign custom_url = site.url | append: site.baseurl %}
  {% assign full_base_url = custom_url | default: site.github.url %}
  <link rel="stylesheet" href="{{ "/css/main.css" | prepend: site.baseurl }}">
  <link rel="canonical" href="{{ page.url | replace:'index.html','' | prepend: full_base_url }}">
  <link rel="alternate" type="application/rss+xml" title="{{ site.title | escape }}" href="{{ "/feed.xml" | prepend: site.baseurl }}">
```

What do others think?

**Comment by Sjlver** [comment] 2016-09-28 16:12
This pattern appears in other places too. For example, `_includes/header.html` generates an "about"-link with an absolute URL. This seems weird to me... I see no reason for it, and it makes local testing difficult.

What do others think?

**Comment by Catsync** [comment] 2016-09-28 16:48
Your line of reasoning is basically why I originally posted this issue in minima instead of jekyll. :)

**Comment by parkr** [comment] 2016-09-28 20:54
@Sjlver I'm fine with that. We have some kinks to work out with setting `baseurl` if none is set but `site.github.url` is present. That's essentially why this is the way it is right now. If we had that feature on GHP then we wouldn't have to rely on `site.github.url`

**Comment by Sjlver** [comment] 2016-09-29 08:36
I've explored this a bit deeper, and I think there are two distinct issues here:

1. Minima (and maybe other Jekyll plugins) use absolute URLs where relative ones would be better suited. In general, I think relative URLs should be used wherever possible, because this reduces compatibility issues.

2. There seems to be a bit of a too strong link between Jekyll and GitHub pages. It leads to weird situations like the one I encountered:
  - If users use vanilla Jekyll, then `site.github.url` is not set. Thus setting `url` to an empty value fixes this issue, as reported by @Catsync .
  - If users use the `github-pages` gem, they have a `jekyll-github-metadata` dependency, which sets `site.github.url` even when building the site locally. Thus pages that use minima are broken in such environments.

I'm not sure if this is intended behavior or not; but in principle I don't think a Jekyll theme should know or care about GitHub pages. I believe avoiding `site.github.url` altogether would be the right thing to do.

PS: I don't want to hijack this issue... let me know if it's better to create a new one
PPS: I don't intend to be unfriendly either... I'm sure there are reasons for the current way of doing things; I'm just confused because my site doesn't work :)

**Comment by davclark** [comment] 2016-10-11 21:35
@Sjlver I think your analysis is correct and I think users with this problem will come here. Your comment is very helpful in this case.

The obvious thing to try was simply reverting to a non-github-pages jekyll install, at which point the above URL link *almost* works, except somehow `main.css` is actually in a `css/` directly, but my *link* in my template ends up pointing to `assets/main.css`.

I've verified that I'm running 2.0. The template link would be set here:

https://github.com/jekyll/minima/blob/v2.0.0/_includes/head.html#L9

I think there may be some issue in which jekyll 3.2(.1) is installing css to `css` even if there is an `assets` folder.

Upshot: I *also* set `gem 'minima', '< 2.0'

Now things work for local development.

**Comment by ashmaroli** [comment] 2016-10-12 02:27
Jekyll 3.2.1 and below will install main.scss only in `<site-root>/css/` and Minima 1.2 n below will always look for it there by default.
Starting Jekyll 3.3, the `css/` folder has moved to `assets/` within Minima 2.0 (and every other updated theme gem). 
Also Minima 2.0 also uses the new `relative_url` filter to set relative url path to stylesheets.. Just a matter of time, till GitHub makes the switch to using the latest versions of Jekyll n Minima
